# A sample Gemfile
source "https://rubygems.org"
gem "activerecord"
gem "sinatra", "~> 2.0.0.beta2"
gem "pry"
gem "sqlite3"

group :test do
  gem "minitest"
  gem "minitest-focus"
  gem "rack-test"
end
